/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Class.Stock_Materials;
import Class.Stock_Spareparts;
import Class.Stock_Tools;
import Class.Supplier;
import DatabaseCon.Database;
import static Interfaces.OrderI.dbReffOrder;
import static Interfaces.SupplierI.dbReffSupplier;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.auth.FirebaseCredentials;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yasiru
 */
public class StockI extends javax.swing.JFrame {

    /**
     * Creates new form StockI
     */ static long Material;
    static DatabaseReference dbReffMaterial;
    Database database;
    
    static long Tools;
    static DatabaseReference dbReffTool;
    
      static long Sparts;
    static DatabaseReference dbReffSparts;
   
     ArrayList<Stock_Materials> Stock_M = new ArrayList<>();
    
    public StockI() throws IOException {
       initializeFirebaseDB();
        initComponents();
         
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void initializeFirebaseDB() throws FileNotFoundException, IOException {
        FileInputStream serviceAccount = new FileInputStream("E:\\packages combine krapu eka\\oms19_2\\oms19_2\\omssystem9798-firebase-adminsdk-938j3-6beddaf76c.json");

        FirebaseOptions options;
        options = new FirebaseOptions.Builder()
                .setCredential(FirebaseCredentials.fromCertificate(serviceAccount))
                .setDatabaseUrl("https://omssystem9798.firebaseio.com/")
                .build();

        FirebaseApp.initializeApp(options);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMID = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        txtMquantity = new javax.swing.JTextField();
        txtMreorder = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShowM = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txtTreorder = new javax.swing.JTextField();
        txtTquantity = new javax.swing.JTextField();
        txtTname = new javax.swing.JTextField();
        txtToolID = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        namesp = new javax.swing.JLabel();
        quansp = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        txtSreorder = new javax.swing.JTextField();
        txtSQuantity = new javax.swing.JTextField();
        txtSname = new javax.swing.JTextField();
        txtsID = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(100, 149, 239));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Materials");
        jLabel2.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Material ID     ");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Material Name");

        lbl3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lbl3.setForeground(new java.awt.Color(102, 102, 102));
        lbl3.setText("Reorder Level");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Quantity");

        txtMID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));
        txtMID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMIDKeyReleased(evt);
            }
        });

        txtMname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtMquantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtMreorder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));

        txtShowM.setColumns(20);
        txtShowM.setRows(5);
        jScrollPane1.setViewportView(txtShowM);

        jButton8.setText("View");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(33, 33, 33)
                                .addComponent(jButton3)
                                .addGap(81, 81, 81))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMreorder))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtMID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtMID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3)
                            .addComponent(txtMreorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton8))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );

        jTabbedPane1.addTab("Materials", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(100, 149, 239));
        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tools");
        jLabel3.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tool ID     ");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Tool Name");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Quantity");

        lbl4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lbl4.setForeground(new java.awt.Color(102, 102, 102));
        lbl4.setText("Reorder Level");

        txtTreorder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtTquantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtTname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtToolID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));
        txtToolID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtToolIDKeyReleased(evt);
            }
        });

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("View All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addGap(48, 48, 48)
                        .addComponent(txtTreorder))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtToolID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTquantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtToolID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTreorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tools", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Sparepart ID     ");

        namesp.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        namesp.setForeground(new java.awt.Color(102, 102, 102));
        namesp.setText("Name");

        quansp.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        quansp.setForeground(new java.awt.Color(102, 102, 102));
        quansp.setText("Quantity");

        lbl5.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lbl5.setForeground(new java.awt.Color(102, 102, 102));
        lbl5.setText("Reorder Level");

        txtSreorder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtSQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtSname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));

        txtsID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 149, 237)));
        txtsID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsIDKeyReleased(evt);
            }
        });

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));

        jButton7.setText("View All");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(100, 149, 239));
        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Spare parts");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(227, 227, 227))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namesp)
                                .addComponent(jLabel15)
                                .addComponent(quansp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtsID, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(lbl5)
                            .addGap(48, 48, 48)
                            .addComponent(txtSreorder, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(251, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(112, 112, 112))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(namesp)
                            .addGap(18, 18, 18)
                            .addComponent(quansp)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lbl5))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSreorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Spare Parts", jPanel4);

        jLabel1.setBackground(new java.awt.Color(100, 149, 239));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Adding Materials
       //Validate
       
       String MaterialID = txtMID.getText();
       String MaterialName = txtMname.getText();
       String MQuantity = txtMquantity.getText();
       String MReorderLevel = txtMreorder.getText();
       
       if(MaterialID.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material ID");
       }else if(MaterialName.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material Name");
       }else if(MQuantity.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material Quantity");
       }else if(MReorderLevel.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material Reorder Level");
       }
        
        try {
            initializeFirebaseDB();
        } catch (IOException ex) {
            Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            dbReffMaterial = FirebaseDatabase.getInstance().getReference("Material").child(txtMID.getText());
            DatabaseReference postsRef = dbReffMaterial;

            DatabaseReference newPostRef = postsRef;
            
            CountDownLatch done = new CountDownLatch(1);
            Stock_Materials mat = new Stock_Materials(txtMID.getText(), txtMname.getText(),Integer.parseInt(txtMquantity.getText()), Integer.parseInt(txtMreorder.getText()));
            newPostRef.setValue(mat);
            JOptionPane.showMessageDialog(this,"Materials Successfully Added");
            
            txtMID.setText(" ");
            txtMname.setText(" ");
            txtMquantity.setText(" ");
            txtMreorder.setText(" ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //View Tools
       
        try{
            initializeFirebaseDB();
       }catch(IOException ex){
             Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       dbReffTool = FirebaseDatabase.getInstance()
             .getReference("Tools");
                dbReffTool.addListenerForSingleValueEvent(new ValueEventListener() 
                {
                                @Override
                                public void onDataChange(DataSnapshot dataSnapshot) 
                                {
                                        Object document = dataSnapshot.getValue();
                                        System.out.println(document);
                                        String doc1=(String)document;
//                                        lblDisplay.setText(doc1);
//                                        lblDisplay.setVisible(true);
//                                       String emailAddress = (String)snapshot.child("emailAddress").getValue();
//				String firstname = (String)dataSnapshot.child("fname").getValue();
//                                String address = (String)dataSnapshot.child("lname").getValue();
//                                String Credit_Limit = (String)dataSnapshot.child("climit:").getValue();
//                                String Contact_No = (String)dataSnapshot.child("contactNo").getValue();
//                                String Email = (String)dataSnapshot.child("email").getValue();
                                
//                                    System.out.println("Supplier Name:"+ (String)dataSnapshot.child("fname").getValue() + "/n");
//                                    System.out.println("Supplier Address:" + (String)dataSnapshot.child("lname").getValue() + "/n");                    
//                                    System.out.println("Credit Limit:" + (String)dataSnapshot.child("climit:").getValue() + "/n"); 
//                                    System.out.println("Contact No:" + (String)dataSnapshot.child("contactNo").getValue() + "/n"); 
//                                    System.out.println("Email:" + (String)dataSnapshot.child("email").getValue() + "/n"); 
                                }


                                @Override
                                public void onCancelled(DatabaseError error) 
                                {
                                    
                                }
                });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Validate
        
       String ToolID = txtToolID.getText();
       String Toolname = txtTname.getText();
       String TQuantity = txtTquantity.getText();
       String TReOrderLevel = txtTreorder.getText();
       
       if(ToolID.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Tool ID");
       }else if(Toolname.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Tool Name");
       }else if(TQuantity.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Tool Quantity");
       }else if(TReOrderLevel.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Tool ReOrder Level");
       }
        
        //Adding Tools
        try {
            initializeFirebaseDB();
        } catch (IOException ex) {
            Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            dbReffTool = FirebaseDatabase.getInstance().getReference("Tools").child(txtToolID.getText());
            DatabaseReference postsRef = dbReffTool;

            DatabaseReference newPostRef = postsRef;
            
            CountDownLatch done = new CountDownLatch(1);
            Stock_Tools tol = new Stock_Tools(txtToolID.getText(), txtToolID.getText(),Integer.parseInt(txtTquantity.getText()), Integer.parseInt(txtTreorder.getText()));
            newPostRef.setValue(tol);
            JOptionPane.showMessageDialog(this,"Tools Successfully Added");
            
            txtToolID.setText(" ");
            txtTname.setText(" ");
            txtTquantity.setText(" ");
            txtTreorder.setText(" ");
        }    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //View Matterials
      
       
        try{
            initializeFirebaseDB();
       }catch(IOException ex){
             Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       dbReffMaterial = FirebaseDatabase.getInstance()
             .getReference("Material");
                dbReffMaterial.addListenerForSingleValueEvent(new ValueEventListener() 
                {
                                @Override
                                public void onDataChange(DataSnapshot dataSnapshot) 
                                {
                                        Object document = dataSnapshot.getValue();
                                        System.out.println(document);
                                        String doc1=(String)document;
//                                        lblDisplay.setText(doc1);
//                                        lblDisplay.setVisible(true);
//                                       String emailAddress = (String)snapshot.child("emailAddress").getValue();
//				String firstname = (String)dataSnapshot.child("fname").getValue();
//                                String address = (String)dataSnapshot.child("lname").getValue();
//                                String Credit_Limit = (String)dataSnapshot.child("climit:").getValue();
//                                String Contact_No = (String)dataSnapshot.child("contactNo").getValue();
//                                String Email = (String)dataSnapshot.child("email").getValue();
                                
//                                    System.out.println("Supplier Name:"+ (String)dataSnapshot.child("fname").getValue() + "/n");
//                                    System.out.println("Supplier Address:" + (String)dataSnapshot.child("lname").getValue() + "/n");                    
//                                    System.out.println("Credit Limit:" + (String)dataSnapshot.child("climit:").getValue() + "/n"); 
//                                    System.out.println("Contact No:" + (String)dataSnapshot.child("contactNo").getValue() + "/n"); 
//                                    System.out.println("Email:" + (String)dataSnapshot.child("email").getValue() + "/n"); 
                                }


                                @Override
                                public void onCancelled(DatabaseError error) 
                                {
                                    
                                }
                });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          //Adding Spareparts
          //Valdate
          
       String SparepartID = txtsID.getText();
       String SparepartName = txtSname.getText();
       String SPquantity = txtSQuantity.getText();
       String SPreorderlvl = txtSreorder.getText();
       
       if(SparepartID.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Spare part ID");
       }else if(SparepartName.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Spare part Name");
       }else if(SPquantity.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Spare Part quantity");
       }else if(SPreorderlvl.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Spare Part Pre-Order Level");
       }
          
        try {
            initializeFirebaseDB();
        } catch (IOException ex) {
            Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            dbReffSparts = FirebaseDatabase.getInstance().getReference("Spare Parts").child(txtsID.getText());
            DatabaseReference postsRef = dbReffSparts;

            DatabaseReference newPostRef = postsRef;
            
            CountDownLatch done = new CountDownLatch(1);
            Stock_Spareparts SP = new Stock_Spareparts(txtsID.getText(), txtSname.getText(),Integer.parseInt(txtSQuantity.getText()), Integer.parseInt(txtSreorder.getText()));
            newPostRef.setValue(SP);
            JOptionPane.showMessageDialog(this,"Tools Successfully Added");
          
             txtsID.setText(" ");
              txtSname.setText(" ");
               txtSQuantity.setText(" ");
                txtSreorder.setText(" ");
        }    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Validate
        
       String MaterialID = txtMID.getText();
       String MaterialName = txtMname.getText();
       String MQuantity = txtMquantity.getText();
       String MReorderLevel = txtMreorder.getText();
       
       if(MaterialID.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material ID");
       }else if(MaterialName.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material Name");
       }else if(MQuantity.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material Quantity");
       }else if(MReorderLevel.equals("")){
                JOptionPane.showMessageDialog(null,"Insert Material Reorder Level");
       }else{
           JOptionPane.showMessageDialog(null,"Material Updated");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtMIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMIDKeyReleased
        // Validate Material ID
        
        String PATTERN="^[M]{1}[0-9]{6}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtMID.getText());
        if(!match.matches()){
            jLabel4.setText("Material ID is Incorrect!");
        }
        else{
            jLabel4.setText(null);
        }
    }//GEN-LAST:event_txtMIDKeyReleased

    private void txtToolIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToolIDKeyReleased
        // Validate Tool ID
        
        String PATTERN="^[T]{1}[0-9]{6}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtToolID.getText());
        if(!match.matches()){
            jLabel5.setText("Tool ID is Incorrect!");
        }
        else{
            jLabel5.setText(null);
        }
    }//GEN-LAST:event_txtToolIDKeyReleased

    private void txtsIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsIDKeyReleased
        // Validate Sparepart ID
        
        String PATTERN="^[S]{1}[P]{1}[0-9]{6}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtsID.getText());
        if(!match.matches()){
            jLabel6.setText("Sparepart ID is Incorrect!");
        }
        else{
            jLabel6.setText(null);
        }
    }//GEN-LAST:event_txtsIDKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // //View Tools
       
        try{
            initializeFirebaseDB();
       }catch(IOException ex){
             Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       dbReffTool = FirebaseDatabase.getInstance()
             .getReference("Spare Parts");
                dbReffTool.addListenerForSingleValueEvent(new ValueEventListener() 
                {
                                @Override
                                public void onDataChange(DataSnapshot dataSnapshot) 
                                {
                                        Object document = dataSnapshot.getValue();
                                        System.out.println(document);
                                        String doc1=(String)document;
//                                        lblDisplay.setText(doc1);
//                                        lblDisplay.setVisible(true);
//                                       String emailAddress = (String)snapshot.child("emailAddress").getValue();
//				String firstname = (String)dataSnapshot.child("fname").getValue();
//                                String address = (String)dataSnapshot.child("lname").getValue();
//                                String Credit_Limit = (String)dataSnapshot.child("climit:").getValue();
//                                String Contact_No = (String)dataSnapshot.child("contactNo").getValue();
//                                String Email = (String)dataSnapshot.child("email").getValue();
                               
                                }


                                @Override
                                public void onCancelled(DatabaseError error) 
                                {
                                    
                                }
                });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       

        dbReffMaterial = FirebaseDatabase.getInstance().getReference().child("Material");

        dbReffMaterial.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot ds) {
                int i=0;
                System.out.println(ds.getChildrenCount());
                for(DataSnapshot d : ds.getChildren()){
                    Stock_M.add(d.getValue(Stock_Materials.class));
                    i++;

                    if(i==ds.getChildrenCount()){
                        for(Stock_Materials s : Stock_M) {
                            if(s.getMaterialID().equals(txtMID.getText())){
                                String details="Material ID : "+s.getMaterialID()+"\n Material Name : "+s.getMaterialName()+"\n Material Quantity : "+s.getMQuantity()+"\n Material Order Level : "+s.getMReorderLevel();
                                txtShowM.setText(details);
                            }
                        }
                    }
                }
            }

            @Override
            public void onCancelled(DatabaseError de) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StockI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StockI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel namesp;
    private javax.swing.JLabel quansp;
    private javax.swing.JTextField txtMID;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtMquantity;
    private javax.swing.JTextField txtMreorder;
    private javax.swing.JTextField txtSQuantity;
    private javax.swing.JTextArea txtShowM;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtSreorder;
    private javax.swing.JTextField txtTname;
    private javax.swing.JTextField txtToolID;
    private javax.swing.JTextField txtTquantity;
    private javax.swing.JTextField txtTreorder;
    private javax.swing.JTextField txtsID;
    // End of variables declaration//GEN-END:variables
}
